# Render.com deployment configuration for Kaggler monorepo
services:
  - type: web
    name: kaggler-backend
    runtime: python
    # Build commands for monorepo - navigate to backend directory
    buildCommand: |
      cd backend
      pip install --upgrade pip
      pip install -r requirements.txt
    # Start command - use production startup script
    startCommand: |
      cd backend
      chmod +x start.sh
      ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.10"
      - key: PORT
        fromService:
          type: web
          name: kaggler-backend
          property: port
      # Add your secrets in Render dashboard (not here for security)
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENAI_API_KEY  
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
    # Health check endpoint
    healthCheckPath: /health
    # Resource plan - using free tier (no payment required)
    plan: free
